### ISSUE TITLE
Feature request: Add `ttl` method

### ISSUE THREAD

**Issue by ediblecode** [rolandstarke/node-cache-manager-fs-hash#10]
Add a `ttl` method to support the `refreshThreshold` property of [node-cache-manager](https://github.com/BryanDonovan/node-cache-manager#refresh-cache-keys-in-background) for _background refreshing_. This would essentially allow a stale-while-revalidate pattern (not exactly SWR - it wouldn't revalidate _every_ time) while using node-cache-manager-fs-hash.

For `refreshThreshold` to work with node-cache-manager it needs "the caching store to provide the `ttl` method.". I guess this is a similar request to https://github.com/isaacs/node-lru-cache/issues/143 (for a bit more background context).

I _think_ this would be easy enough to implement - the `expireTime` property stored in each JSON file could easily be used to calculate the ttl of the key. And it could still `await` the lock to avoid conflicts and support `cluster`. In fact, it would probably be very similar to the current `get` method, but would return the ttl rather than `data.val`.

Happy to have a go at a Pull Request!

**Comment by rolandstarke** [comment]
Thank you for the input. I added the `ttl` method and released it under version 1.0.0.

**Comment by ediblecode** [comment]
@rolandstarke amazing, that was well quick, great work, thank you!
