### ISSUE TITLE
store.get is not a function

### ISSUE THREAD

**Issue by sayjeyhi** [rolandstarke/node-cache-manager-fs-hash#16]
Hi 

I am using `cache-manager` : `"^5.5.1",`  and I get an error when I try to use `node-cache-manager-fs-hash`
```bash
 ⨯ ../node_modules/cache-manager/dist/caching.js (77:34) @ get
 ⨯ TypeError: store.get is not a function
```

It seems the package is not compatible with the new versions of `cache-manager`.

here is my code:

```ts
import { caching } from 'cache-manager';
import fsStore from 'cache-manager-fs-hash';

async function CacheService() {
  const cacheService = await caching({
    options: {
      path: 'diskcache',
      // time to life in seconds
      subdirs: true,
      // path for cached files
      ttl: 60 * 60, // create subdirectories to reduce the
      // files in a single dir (default: false)
      zip: true, // zip files to save diskspace (default: false)
    },
    store: fsStore,
  });

  const get = (key: string) => {
    console.log('CacheService get', cacheService);
    return cacheService.get(key);
  };

  const set = (key: string, value: any) => {
    return cacheService.set(key, value);
  };

  return {
    get,
    set,
  };
}

export default CacheService;

```

**Comment by lennyhans** [comment]
Probably is related to this PR, which seems to address the problem
- https://github.com/rolandstarke/node-cache-manager-fs-hash/pull/11

If you check, the current master exports a `create` method instead of the store itself. Can you try use that as the store?
```javascript
import { create as fsStore } from 'cache-manager-fs-hash';
const cacheService = await caching({
    options: {
      // ... options
    },
    store: fsStore,
  });

```

**Comment by rolandstarke** [comment]
Based on the source code https://github.com/jaredwray/cache-manager/blob/v5.5.0/src/caching.ts#L69 it looks like the caching method changed, there is no store option anymore.

I think the new way would be to pass the store object as the first param like its done in https://github.com/huijiewei/cache-manager-sqlite 
```javascript
const memStoreCache = await cacheManager.caching(sqliteStore({cacheTableName: 'caches'}));
````

**Comment by rolandstarke** [comment]
I published version 2 of the `node-cache-manager-fs-hash`  library and updated the Readme examples. The library should now work with `cache-manager` version 5.
