### ISSUE TITLE
using key as filename

### ISSUE THREAD

**Issue by amit777** [rolandstarke/node-cache-manager-fs-hash#5]
Hi, I like how this module is designed for cluster scenarios.  I was wondering if there is any reason to not just use the cache key as the filename rather than the md5 hash?  Is it to protect from potentially badly formatted keys?

**Comment by rolandstarke** [comment]
Hi, thank you.

Yes because of that. Other reasons could be that not all chars are allowed in filenames, prevention of long filenames, problems with case insensitivity on some systems and even distribution in the folders if one uses the `subdirs: true` option.
