### ISSUE TITLE
When using subdirs:true you may get an error EEXIST: file already exists, mkdir

### ISSUE THREAD

**Issue by wixbit** [rolandstarke/node-cache-manager-fs-hash#6]
Could be fixed by sending { recursive: true } to mkdir

**Comment by rolandstarke** [comment]
Hey, thank you very much for the report.

This should fix it: https://github.com/rolandstarke/node-cache-manager-fs-hash/commit/af52d2d3a7c28fcbf9533d1ea1d5c29f38c0c54f

(recursive option sounds nice. I kept it this way now to keep it node 8 compatible.)
